name: Build and Deploy on pokemon Auto Chess Assets
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy dist folder to another repository
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source_folder: 'app/public/dist/client/assets'
          destination_repo: 'keldaanCommunity/pokemonAutoChessAssets'
          destination_folder: 'assets'
          user_email: 'keldaan.ag@gmail.com'
          user_name: 'keldaan'
          commit_msg: 'Update assets'
          destination_branch: 'main'